import { supabase } from '@/integrations/supabase/client';

export interface CheckoutLinkData {
  planSlug: string;
  companyName?: string;
  vatId?: string;
  email?: string;
  phone?: string;
  country?: string;
  city?: string;
  postalCode?: string;
  address?: string;
  customPrice?: number;
  billingInterval?: string;
  paymentMethods: string[];
  description?: string;
  winerimUserId?: number;
  currency?: string;
}

export interface CheckoutLinkResult {
  code: string;
  url: string;
}

export async function createCheckoutLink(data: CheckoutLinkData): Promise<CheckoutLinkResult> {
  const { data: row, error } = await supabase
    .from('checkout_links')
    .insert({
      code: '', // auto-generated by trigger
      plan_slug: data.planSlug,
      company_name: data.companyName || null,
      vat_id: data.vatId || null,
      email: data.email || null,
      phone: data.phone || null,
      country: data.country || null,
      city: data.city || null,
      postal_code: data.postalCode || null,
      address: data.address || null,
      custom_price: data.customPrice ?? null,
      billing_interval: data.billingInterval || null,
      payment_methods: data.paymentMethods,
      description: data.description || null,
      currency: data.currency || 'EUR',
    })
    .select('code')
    .single();

  if (error || !row) {
    throw new Error(error?.message || 'Error al crear el enlace');
  }

  const url = `${window.location.origin}/p/${row.code}`;
  return { code: row.code, url };
}

export async function getCheckoutLink(code: string): Promise<CheckoutLinkData | null> {
  const { data, error } = await supabase
    .from('checkout_links')
    .select('*')
    .eq('code', code)
    .single();

  if (error || !data) return null;

  return {
    planSlug: data.plan_slug,
    companyName: data.company_name ?? undefined,
    vatId: data.vat_id ?? undefined,
    email: data.email ?? undefined,
    phone: data.phone ?? undefined,
    country: data.country ?? undefined,
    city: data.city ?? undefined,
    postalCode: data.postal_code ?? undefined,
    address: data.address ?? undefined,
    customPrice: data.custom_price ? Number(data.custom_price) : undefined,
    billingInterval: data.billing_interval ?? undefined,
    paymentMethods: data.payment_methods,
    description: data.description ?? undefined,
    winerimUserId: data.winerim_user_id ?? undefined,
    currency: data.currency ?? undefined,
  };
}
