project_id = "zgmlcqdjzvkrsofjwhne"

[functions.create-checkout]
verify_jwt = false

[functions.send-payment-request]
verify_jwt = false

[functions.send-payment-notification]
verify_jwt = false

[functions.send-proforma]
verify_jwt = false

[functions.migrate-subscriptions]
verify_jwt = false