export interface IntlPlan {
  planSlug: string;
  name: Record<string, string>;
  price: { EUR: number; USD: number };
  period: 'monthly' | 'annual';
  features: Record<string, string[]>;
  savings?: Record<string, string>;
  highlight?: boolean;
}

export const intlPlans: IntlPlan[] = [
  {
    planSlug: 'monthly',
    name: { en: 'Monthly', es: 'Mensual', it: 'Mensile' },
    price: { EUR: 149, USD: 149 },
    period: 'monthly',
    features: {
      en: [
        'Full platform access',
        'Advanced sales analytics',
        'Unlimited staff training',
        'AI pairing recommendations',
        'POS integrations',
        'Priority support',
      ],
      es: [
        'Acceso completo a la plataforma',
        'Analítica avanzada de ventas',
        'Formación de sala ilimitada',
        'Recomendaciones de maridaje IA',
        'Integraciones con TPV',
        'Soporte prioritario',
      ],
      it: [
        'Accesso completo alla piattaforma',
        'Analisi avanzate delle vendite',
        'Formazione illimitata del personale',
        'Raccomandazioni di abbinamento IA',
        'Integrazioni POS',
        'Supporto prioritario',
      ],
    },
  },
  {
    planSlug: 'biannual',
    name: { en: 'Biannual', es: 'Semestral', it: 'Semestrale' },
    price: { EUR: 795, USD: 795 },
    period: 'annual',
    features: {
      en: [
        'Everything in Monthly',
        'Save €99 (11% off)',
        'Personalized onboarding',
        'Quarterly consulting',
      ],
      es: [
        'Todo lo del plan Mensual',
        'Ahorra 99€ (11% descuento)',
        'Onboarding personalizado',
        'Consultoría trimestral',
      ],
      it: [
        'Tutto del piano Mensile',
        'Risparmia 99€ (11% di sconto)',
        'Onboarding personalizzato',
        'Consulenza trimestrale',
      ],
    },
    savings: { en: 'Save €99', es: 'Ahorra 99€', it: 'Risparmia 99€' },
  },
  {
    planSlug: 'annual',
    name: { en: 'Annual', es: 'Anual', it: 'Annuale' },
    price: { EUR: 1199, USD: 1199 },
    period: 'annual',
    features: {
      en: [
        'Everything in Monthly',
        'Save €589 (33% off)',
        'Personalized onboarding',
        'Quarterly consulting',
        'Early access to new features',
        'Dedicated account manager',
      ],
      es: [
        'Todo lo del plan Mensual',
        'Ahorra 589€ (33% descuento)',
        'Onboarding personalizado',
        'Consultoría trimestral',
        'Acceso anticipado a novedades',
        'Account manager dedicado',
      ],
      it: [
        'Tutto del piano Mensile',
        'Risparmia 589€ (33% di sconto)',
        'Onboarding personalizzato',
        'Consulenza trimestrale',
        'Accesso anticipato alle novità',
        'Account manager dedicato',
      ],
    },
    savings: { en: 'Save €589', es: 'Risparmia 589€', it: 'Risparmia 589€' },
    highlight: true,
  },
];

export type IntlLang = 'en' | 'es' | 'it';
export type IntlCurrency = 'EUR' | 'USD';

export const langLabels: Record<IntlLang, string> = {
  en: 'English',
  es: 'Español',
  it: 'Italiano',
};

export const i18n: Record<IntlLang, Record<string, string>> = {
  en: {
    heroTag: 'The Wine Revolution',
    heroTitle: 'The software that helps your restaurant',
    heroHighlight: 'sell more wine',
    heroDescription: 'Analytics, staff training, and smart recommendations to turn your wine list into a profit machine.',
    ctaPrimary: 'Get started',
    ctaSecondary: 'Talk to sales',
    pricingTitle: 'Plans designed for hospitality',
    pricingSubtitle: 'No commitment. Cancel anytime.',
    monthly: 'Monthly',
    annual: 'Annual',
    choosePlan: 'Choose plan',
    mostPopular: 'Most popular',
    perMonth: '/mo',
    perYear: '/yr',
    equivMonth: '/mo billed annually',
    benefitSell: 'Sell more wine',
    benefitSellDesc: 'Smart recommendations that increase average ticket',
    benefitMargin: 'Improve margins',
    benefitMarginDesc: 'Profitability analytics by bottle and supplier',
    benefitTeam: 'Train your team',
    benefitTeamDesc: 'Materials and training so your staff sells with confidence',
    benefitData: 'Decide with data',
    benefitDataDesc: 'Dashboard of rotation, trends, and opportunities',
    terms: 'Terms',
    privacy: 'Privacy',
    contact: 'Contact',
    currency: 'Currency',
  },
  es: {
    heroTag: 'La reVINOlución',
    heroTitle: 'El software que hace que tu restaurante',
    heroHighlight: 'venda más vino',
    heroDescription: 'Analítica, formación de sala y recomendaciones inteligentes para convertir tu carta de vinos en una máquina de generar margen.',
    ctaPrimary: 'Empezar ahora',
    ctaSecondary: 'Hablar con ventas',
    pricingTitle: 'Planes diseñados para hostelería',
    pricingSubtitle: 'Sin permanencia. Cancela cuando quieras.',
    monthly: 'Mensual',
    annual: 'Anual',
    choosePlan: 'Elegir plan',
    mostPopular: 'Más popular',
    perMonth: '/mes',
    perYear: '/año',
    equivMonth: '/mes facturado anual',
    benefitSell: 'Vende más vino',
    benefitSellDesc: 'Recomendaciones inteligentes que aumentan el ticket medio',
    benefitMargin: 'Mejora el margen',
    benefitMarginDesc: 'Analítica de rentabilidad por botella y proveedor',
    benefitTeam: 'Forma a tu equipo',
    benefitTeamDesc: 'Fichas y formación para que tu sala venda con confianza',
    benefitData: 'Decide con datos',
    benefitDataDesc: 'Dashboard de rotación, tendencias y oportunidades',
    terms: 'Condiciones',
    privacy: 'Privacidad',
    contact: 'Contacto',
    currency: 'Divisa',
  },
  it: {
    heroTag: 'La riVINOluzione',
    heroTitle: 'Il software che aiuta il tuo ristorante a',
    heroHighlight: 'vendere più vino',
    heroDescription: 'Analisi, formazione del personale e raccomandazioni intelligenti per trasformare la tua carta dei vini in una macchina da profitto.',
    ctaPrimary: 'Inizia ora',
    ctaSecondary: 'Parla con le vendite',
    pricingTitle: 'Piani pensati per la ristorazione',
    pricingSubtitle: 'Senza impegno. Cancella quando vuoi.',
    monthly: 'Mensile',
    annual: 'Annuale',
    choosePlan: 'Scegli piano',
    mostPopular: 'Più popolare',
    perMonth: '/mese',
    perYear: '/anno',
    equivMonth: '/mese fatturato annuale',
    benefitSell: 'Vendi più vino',
    benefitSellDesc: 'Raccomandazioni intelligenti che aumentano lo scontrino medio',
    benefitMargin: 'Migliora il margine',
    benefitMarginDesc: 'Analisi della redditività per bottiglia e fornitore',
    benefitTeam: 'Forma il tuo team',
    benefitTeamDesc: 'Schede e formazione per vendere con fiducia',
    benefitData: 'Decidi con i dati',
    benefitDataDesc: 'Dashboard di rotazione, tendenze e opportunità',
    terms: 'Termini',
    privacy: 'Privacy',
    contact: 'Contatto',
    currency: 'Valuta',
  },
};
