export interface IntlPlan {
  planSlug: string;
  name: Record<string, string>;
  price: { EUR: number };
  period: 'monthly' | 'annual';
  features: Record<string, string[]>;
  savings?: Record<string, string>;
  highlight?: boolean;
}

export const intlPlans: IntlPlan[] = [
  {
    planSlug: 'monthly',
    name: { en: 'Monthly', es: 'Mensual', it: 'Mensile' },
    price: { EUR: 149 },
    period: 'monthly',
    features: {
      en: ['Full platform access', 'All features included', 'Priority support', 'No commitment'],
      es: ['Acceso completo a la plataforma', 'Todas las funcionalidades incluidas', 'Soporte prioritario', 'Sin permanencia'],
      it: ['Accesso completo alla piattaforma', 'Tutte le funzionalità incluse', 'Supporto prioritario', 'Senza impegno'],
    },
  },
  {
    planSlug: 'biannual',
    name: { en: 'Biannual', es: 'Semestral', it: 'Semestrale' },
    price: { EUR: 795 },
    period: 'annual',
    features: {
      en: ['Everything in Monthly', 'Save €99 (11% off)', 'Personalized onboarding', 'Quarterly consulting'],
      es: ['Todo lo del plan Mensual', 'Ahorra 99€ (11% descuento)', 'Onboarding personalizado', 'Consultoría trimestral'],
      it: ['Tutto del piano Mensile', 'Risparmia 99€ (11% di sconto)', 'Onboarding personalizzato', 'Consulenza trimestrale'],
    },
    savings: { en: 'Save €99', es: 'Ahorra 99€', it: 'Risparmia 99€' },
  },
  {
    planSlug: 'annual',
    name: { en: 'Annual', es: 'Anual', it: 'Annuale' },
    price: { EUR: 1199 },
    period: 'annual',
    features: {
      en: ['Everything in Monthly', 'Save €589 (33% off)', 'Personalized onboarding', 'Quarterly consulting', 'Early access to new features', 'Dedicated account manager'],
      es: ['Todo lo del plan Mensual', 'Ahorra 589€ (33% descuento)', 'Onboarding personalizado', 'Consultoría trimestral', 'Acceso anticipado a novedades', 'Account manager dedicado'],
      it: ['Tutto del piano Mensile', 'Risparmia 589€ (33% di sconto)', 'Onboarding personalizzato', 'Consulenza trimestrale', 'Accesso anticipato alle novità', 'Account manager dedicato'],
    },
    savings: { en: 'Save €589', es: 'Risparmia 589€', it: 'Risparmia 589€' },
    highlight: true,
  },
];

export const allPlanFeaturesIntl: Record<string, string[]> = {
  en: [
    'Interactive digital wine list with QR & link',
    'Dynamic filters and wine comparator',
    'Automatic multi-language (4 languages)',
    'AI-powered food & wine pairings',
    'Smart wine-dish recommendations',
    'AI-generated wine profiles',
    'Advanced sales analytics',
    'KPIs: average ticket, rotation, margin',
    'Stock & inventory control',
    'Automatic low-stock alerts',
    'Pricing & margin analysis',
    'Detection of non-rotating wines',
    'Integrated staff training',
    'Decision Center with prioritized actions',
    'POS integrations',
    'Priority support',
  ],
  es: [
    'Carta digital interactiva con QR y link',
    'Filtros dinámicos y comparador de vinos',
    'Multiidioma automático (4 idiomas)',
    'Maridajes automáticos con IA',
    'Recomendaciones inteligentes vino-plato',
    'Fichas de vino generadas por IA',
    'Analítica avanzada de ventas',
    'KPIs: ticket medio, rotación, margen',
    'Control de stock e inventario',
    'Alertas de stock bajo automáticas',
    'Pricing y análisis de márgenes',
    'Detección de vinos sin rotación',
    'Formación de sala integrada',
    'Decision Center con acciones priorizadas',
    'Integraciones con TPV',
    'Soporte prioritario',
  ],
  it: [
    'Carta dei vini digitale interattiva con QR e link',
    'Filtri dinamici e comparatore di vini',
    'Multilingua automatico (4 lingue)',
    'Abbinamenti automatici con IA',
    'Raccomandazioni intelligenti vino-piatto',
    'Schede vino generate dall\'IA',
    'Analisi avanzate delle vendite',
    'KPI: scontrino medio, rotazione, margine',
    'Controllo stock e inventario',
    'Avvisi automatici di stock basso',
    'Pricing e analisi dei margini',
    'Rilevamento vini senza rotazione',
    'Formazione del personale integrata',
    'Decision Center con azioni prioritarie',
    'Integrazioni POS',
    'Supporto prioritario',
  ],
};

export type IntlLang = 'en' | 'es' | 'it';
export type IntlCurrency = 'EUR' | 'USD';

export const langLabels: Record<IntlLang, string> = {
  en: 'English',
  es: 'Español',
  it: 'Italiano',
};

export const i18n: Record<IntlLang, Record<string, string>> = {
  en: {
    heroTag: 'The Wine Revolution',
    heroTitle: 'Sell more wine.',
    heroHighlight: 'Improve margins. Control your cellar.',
    heroDescription: 'Winerim turns your wine list into a sales, analytics, and management tool — powered by AI, no sommelier needed.',
    ctaPrimary: 'Get started',
    ctaSecondary: 'Talk to sales',
    viewPlans: 'View plans',
    pricingTitle: 'Plans designed for hospitality',
    pricingSubtitle: 'No commitment. Cancel anytime. Everything included.',
    monthly: 'Monthly',
    annual: 'Annual',
    choosePlan: 'Subscribe now',
    mostPopular: 'Most popular',
    perMonth: '/mo',
    perYear: '/yr',
    equivMonth: '/mo billed annually',
    terms: 'Terms',
    privacy: 'Privacy',
    contact: 'Contact',
    problemTitle: 'Wine should be your best margin… but rarely is.',
    problem1: 'Your wine list doesn\'t sell — it just informs. Wine is undersold.',
    problem2: 'Staff lacks time or knowledge to recommend wines.',
    problem3: 'Wines sit without rotation, references poorly positioned.',
    problem4: 'No clear data to make purchasing or pricing decisions.',
    solutionLabel: 'The solution',
    solutionTitle: 'Your wine list becomes 5 tools',
    solutionSubtitle: 'Winerim transforms your wine list into a tool for sales, recommendation, management, analytics, and training.',
    featuresTitle: 'Everything included in every plan',
    featuresSubtitle: 'No extra modules or hidden costs. Full access from day one.',
    testimonialsTitle: 'What our clients say',
    statsManaged: 'cellars managed',
    statsCountries: 'countries',
    statsTicket: 'avg ticket increase',
    ctaTitle: 'Is your wine list performing as it should?',
    ctaSubtitle: 'Start today and turn your wine list into a sales tool from day one.',
    ctaButton: 'View plans & start',
    ctaTalk: 'Talk to an advisor',
    guarantee: '🔒 Secure payment · No commitment · Cancel anytime',
    toolSales: 'Sales tool',
    toolSalesDesc: 'The list guides diners toward better decisions and converts more. Filters, comparator, and multi-language navigation.',
    toolAI: 'AI recommendations',
    toolAIDesc: 'Automatic wine-food pairings for every diner and context. AI-generated wine profiles.',
    toolCellar: 'Cellar management',
    toolCellarDesc: 'Stock, pricing, rotation, and availability from a single panel. Automatic low-stock alerts.',
    toolAnalytics: 'Advanced analytics',
    toolAnalyticsDesc: 'Sales KPIs, average ticket, rotation, margin per reference. Diner behavior data.',
    toolTraining: 'Staff training',
    toolTrainingDesc: 'Your team recommends wine with confidence from day one, without relying on a sommelier.',
    toolDecision: 'Decision Center',
    toolDecisionDesc: 'Interpret insights, prioritize actions, and make clearer decisions about your list, pricing, stock, and purchasing.',
  },
  es: {
    heroTag: 'La reVINOlución',
    heroTitle: 'Vende más vino.',
    heroHighlight: 'Mejora márgenes. Controla tu bodega.',
    heroDescription: 'Winerim convierte tu carta de vinos en una herramienta de venta, análisis y gestión — con IA, sin depender del sommelier.',
    ctaPrimary: 'Empezar ahora',
    ctaSecondary: 'Hablar con ventas',
    viewPlans: 'Ver planes',
    pricingTitle: 'Planes diseñados para hostelería',
    pricingSubtitle: 'Sin permanencia. Cancela cuando quieras. Todo incluido.',
    monthly: 'Mensual',
    annual: 'Anual',
    choosePlan: 'Contratar ahora',
    mostPopular: 'Más popular',
    perMonth: '/mes',
    perYear: '/año',
    equivMonth: '/mes facturado anual',
    terms: 'Condiciones',
    privacy: 'Privacidad',
    contact: 'Contacto',
    problemTitle: 'El vino debería ser tu mayor margen… pero rara vez lo es.',
    problem1: 'La carta de vinos no vende, solo informa. El vino está infravendido.',
    problem2: 'El equipo de sala no tiene tiempo ni conocimiento para recomendar vinos.',
    problem3: 'Hay vinos parados sin rotación y referencias mal posicionadas.',
    problem4: 'No hay datos claros para tomar decisiones de compra ni pricing.',
    solutionLabel: 'La solución',
    solutionTitle: 'Tu carta de vinos se convierte en 5 herramientas',
    solutionSubtitle: 'Winerim transforma tu carta en una herramienta de venta, recomendación, gestión, análisis y formación.',
    featuresTitle: 'Todo incluido en cada plan',
    featuresSubtitle: 'Sin módulos extra ni costes ocultos. Acceso completo desde el primer día.',
    testimonialsTitle: 'Lo que dicen nuestros clientes',
    statsManaged: 'bodegas gestionadas',
    statsCountries: 'países',
    statsTicket: 'aumento ticket medio',
    ctaTitle: '¿Tu carta de vinos rinde lo que debería?',
    ctaSubtitle: 'Empieza hoy y convierte tu carta en una herramienta de venta desde el primer día.',
    ctaButton: 'Ver planes y empezar',
    ctaTalk: 'Hablar con un asesor',
    guarantee: '🔒 Pago seguro · Sin permanencia · Cancela cuando quieras',
    toolSales: 'Herramienta de venta',
    toolSalesDesc: 'La carta guía al comensal hacia mejores decisiones y convierte más. Filtros, comparador y navegación multiidioma.',
    toolAI: 'Recomendación con IA',
    toolAIDesc: 'Maridajes automáticos vino-plato para cada comensal y contexto. Fichas generadas con inteligencia artificial.',
    toolCellar: 'Gestión de bodega',
    toolCellarDesc: 'Stock, pricing, rotación y disponibilidad desde un solo panel. Alertas automáticas de stock bajo.',
    toolAnalytics: 'Analítica avanzada',
    toolAnalyticsDesc: 'KPIs de venta, ticket medio, rotación, margen por referencia. Datos de comportamiento del comensal.',
    toolTraining: 'Formación de sala',
    toolTrainingDesc: 'El equipo recomienda vino con confianza desde el primer día, sin depender del sumiller.',
    toolDecision: 'Decision Center',
    toolDecisionDesc: 'Interpreta insights, prioriza acciones y toma decisiones más claras sobre carta, pricing, stock y compras.',
  },
  it: {
    heroTag: 'La riVINOluzione',
    heroTitle: 'Vendi più vino.',
    heroHighlight: 'Migliora i margini. Controlla la tua cantina.',
    heroDescription: 'Winerim trasforma la tua carta dei vini in uno strumento di vendita, analisi e gestione — con IA, senza dipendere dal sommelier.',
    ctaPrimary: 'Inizia ora',
    ctaSecondary: 'Parla con le vendite',
    viewPlans: 'Vedi piani',
    pricingTitle: 'Piani pensati per la ristorazione',
    pricingSubtitle: 'Senza impegno. Cancella quando vuoi. Tutto incluso.',
    monthly: 'Mensile',
    annual: 'Annuale',
    choosePlan: 'Abbonati ora',
    mostPopular: 'Più popolare',
    perMonth: '/mese',
    perYear: '/anno',
    equivMonth: '/mese fatturato annuale',
    terms: 'Termini',
    privacy: 'Privacy',
    contact: 'Contatto',
    problemTitle: 'Il vino dovrebbe essere il tuo margine migliore… ma raramente lo è.',
    problem1: 'La carta dei vini non vende, informa soltanto. Il vino è sotto-venduto.',
    problem2: 'Il personale non ha tempo né conoscenze per consigliare vini.',
    problem3: 'Ci sono vini fermi senza rotazione e referenze mal posizionate.',
    problem4: 'Non ci sono dati chiari per prendere decisioni di acquisto o pricing.',
    solutionLabel: 'La soluzione',
    solutionTitle: 'La tua carta dei vini diventa 5 strumenti',
    solutionSubtitle: 'Winerim trasforma la tua carta in uno strumento di vendita, raccomandazione, gestione, analisi e formazione.',
    featuresTitle: 'Tutto incluso in ogni piano',
    featuresSubtitle: 'Nessun modulo extra o costi nascosti. Accesso completo dal primo giorno.',
    testimonialsTitle: 'Cosa dicono i nostri clienti',
    statsManaged: 'cantine gestite',
    statsCountries: 'paesi',
    statsTicket: 'aumento scontrino medio',
    ctaTitle: 'La tua carta dei vini rende quanto dovrebbe?',
    ctaSubtitle: 'Inizia oggi e trasforma la tua carta in uno strumento di vendita dal primo giorno.',
    ctaButton: 'Vedi piani e inizia',
    ctaTalk: 'Parla con un consulente',
    guarantee: '🔒 Pagamento sicuro · Senza impegno · Cancella quando vuoi',
    toolSales: 'Strumento di vendita',
    toolSalesDesc: 'La carta guida il commensale verso scelte migliori e converte di più. Filtri, comparatore e navigazione multilingua.',
    toolAI: 'Raccomandazione con IA',
    toolAIDesc: 'Abbinamenti automatici vino-piatto per ogni commensale e contesto. Schede generate con intelligenza artificiale.',
    toolCellar: 'Gestione cantina',
    toolCellarDesc: 'Stock, pricing, rotazione e disponibilità da un unico pannello. Avvisi automatici di stock basso.',
    toolAnalytics: 'Analisi avanzata',
    toolAnalyticsDesc: 'KPI di vendita, scontrino medio, rotazione, margine per referenza. Dati sul comportamento del commensale.',
    toolTraining: 'Formazione del personale',
    toolTrainingDesc: 'Il team consiglia vini con fiducia dal primo giorno, senza dipendere dal sommelier.',
    toolDecision: 'Decision Center',
    toolDecisionDesc: 'Interpreta insight, prioritizza azioni e prendi decisioni più chiare su carta, pricing, stock e acquisti.',
  },
};
